package it.polito.wa2.g17.ticketcatalogueservice.utils

enum class AdminPermissions {
    LOGIN_SERVICE_MANAGE_USERS,
    LOGIN_SERVICE_MANAGE_ADMINS,
    TURNSTILE_SERVICE_MANAGE_TURNSTILE,
    TRAVELER_SERVICE_MANAGE_TRAVELERS,
    TRAVELER_SERVICE_MANAGE_REPORTS,
    TICKET_CATALOGUE_SERVICE_MANAGE_TICKETS,
    TICKET_CATALOGUE_SERVICE_MANAGE_ORDERS,
    PAYMENT_SERVICE_MANAGE_TRANSACTIONS
}